### PR TITLE
Update FlightMastersClassic.lua

### PR DESCRIPTION
**Pull request by mwpatrick**
Fix missing Alliance flight point in Ashenvale. Prefix names with Flight so it is obvious on the map what they are.

### CODE REVIEW

**Comment by datagutten** [comment]
I would prefer adding the "Flight" prefix in the format string in the TomTom:AddWaypoint call in FlightMastersClassic.lua. That way we keep the NPC name to be used in other cases.

**Comment by mwpatrick** [comment]
That’s fine. I’m out of town for a week. I can do that when I get back if you don’t get to it first.

**Comment by mwpatrick** [comment]
Additional question: does some kind of version number need to be bumped? Wondering how addon apps like Twitch would know a new version is up.

**Comment by datagutten** [comment]
The version number in the toc file is increased and a tag is added on git.

**Comment by mwpatrick** [comment]
Updated to move the Flight: tag to the TomTom:AddWaypoint call and bumped the TOC version number (you mentioned that is part of what would notify addon managers that a new version is out)

**Comment by datagutten** [comment]
Daelyshia added in d6059995624cfef164d8297c60ae37d7b0d7cdb0

**Pull request closed without merging**
